apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
  labels:
    name: replication-controller 
  annotations:
    description: ini adalah replication controller
spec:
  replicas: 3
  selector:
    team: learn
  template:
    metadata:
      name: nginx
      labels:
        team: learn
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1