apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: learn
    version: 1.0.0
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80