---
# -- (Optional) When using a custom network
networks:
  traefik:
    external: true
services:
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      # - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=7D9cRHvgY7V8m8elJsuyTDtqwcUZ1DYgKMtISXuL
    # -- (Optional) When using a custom network
    networks:
      - traefik
    restart: unless-stopped