---
services:
    uptime-kuma:
        ports:
            - 3001:3001
        volumes:
            - ./data:/app/data
        image: louislam/uptime-kuma:1
        networks:
            - default_network

networks:
    default_network:
        external: true